spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  context-path: /sell
  port: 8080